In [1]:
datos = {'manzanas': [3,2,0,1], 'naranjas': [0,3,7,2]}
datos

{'manzanas': [3, 2, 0, 1], 'naranjas': [0, 3, 7, 2]}

In [3]:
import pandas as pd
compras = pd.DataFrame(datos)
compras

manzanas  naranjas
0         3         0
1         2         3
2         0         7
3         1         2

In [5]:
compras = pd.DataFrame(datos, index= ['Juno', 'Robert', 'Lily', 'David'])
compras

manzanas  naranjas
Juno           3         0
Robert         2         3
Lily           0         7
David          1         2

In [6]:
compras.index

Index(['Juno', 'Robert', 'Lily', 'David'], dtype='object')

In [7]:
compras.values

array([[3, 0],
       [2, 3],
       [0, 7],
       [1, 2]])

In [8]:
compras.columns

Index(['manzanas', 'naranjas'], dtype='object')

In [9]:
compras.axes

[Index(['Juno', 'Robert', 'Lily', 'David'], dtype='object'),
 Index(['manzanas', 'naranjas'], dtype='object')]

In [12]:
compras.index.name = 'Clientes'
compras.columns.name = 'Frutas'
compras

Frutas    manzanas  naranjas
Clientes                    
Juno             3         0
Robert           2         3
Lily             0         7
David            1         2

In [13]:
compras.values

array([[3, 0],
       [2, 3],
       [0, 7],
       [1, 2]])

In [14]:
compras.shape

(4, 2)

In [15]:
""" Creacion de dtaframes """

' Creacion de dtaframes '

In [25]:
elementos = {
    "Numero atómico": [1,6,4,88],
    "Masa atómica": [1.008, 12.011, 107.87, 226],
    "Familia": ["No metales", "No Metales", "Metal", "Metal"]
}

elementos

{'Numero atómico': [1, 6, 4, 88],
 'Masa atómica': [1.008, 12.011, 107.87, 226],
 'Familia': ['No metales', 'No Metales', 'Metal', 'Metal']}

In [26]:
tabla = pd.DataFrame(elementos)
tabla

Numero atómico  Masa atómica     Familia
0               1         1.008  No metales
1               6        12.011  No Metales
2               4       107.870       Metal
3              88       226.000       Metal

In [30]:
tabla = pd.DataFrame(elementos,index = ["H", "C", "Ag", "Ra"],
columns = ["Familia", "Numero atómico", "Masa atómica"])
tabla

Familia  Numero atómico  Masa atómica
H   No metales               1         1.008
C   No Metales               6        12.011
Ag       Metal               4       107.870
Ra       Metal              88       226.000

In [22]:
import numpy as np

unidades_datos = np.array([[2,5,3,2], [4,6,7,2], [3,2,4,1]])
unidades_datos

array([[2, 5, 3, 2],
       [4, 6, 7, 2],
       [3, 2, 4, 1]])

In [23]:
unidades = pd.DataFrame(unidades_datos)
unidades

0  1  2  3
0  2  5  3  2
1  4  6  7  2
2  3  2  4  1

In [31]:
unidades = pd.DataFrame(unidades_datos, index= [2015, 2016, 2017],
columns = ["Ag", "Au", "Cu", "Pt"])
unidades

Ag  Au  Cu  Pt
2015   2   5   3   2
2016   4   6   7   2
2017   3   2   4   1

In [32]:
u_2015 = {"Ag":2,  "Au":5, "Cu": 3, "Pt":2}
u_2016 = {"Ag":4,  "Au":6, "Cu": 7, "Pt":2}
u_2017 = {"Ag":3,  "Au":2, "Cu": 4, "Pt":1}

In [34]:
unidades = pd.DataFrame([u_2015, u_2016, u_2017], index= [2015,2016,2017])
unidades

Ag  Au  Cu  Pt
2015   2   5   3   2
2016   4   6   7   2
2017   3   2   4   1

In [36]:
#metodos
entrada = pd.Series([11, 18,12,16, 9 ,16,22,28,31,29,30,12],
index = ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"])

entrada

ene    11
feb    18
mar    12
abr    16
may     9
jun    16
jul    22
ago    28
sep    31
oct    29
nov    30
dic    12
dtype: int64

In [38]:
entrada.head(10)

ene    11
feb    18
mar    12
abr    16
may     9
jun    16
jul    22
ago    28
sep    31
oct    29
dtype: int64

In [40]:
entrada.tail(7)

jun    16
jul    22
ago    28
sep    31
oct    29
nov    30
dic    12
dtype: int64

In [45]:
entrada.sample(6)

mar    12
may     9
feb    18
ene    11
oct    29
sep    31
dtype: int64

In [47]:
salida = pd.Series([9, 26, 18, 15, 6, 22, 19, 25, 34, 22, 21, 14],
index = ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"])
salida

ene     9
feb    26
mar    18
abr    15
may     6
jun    22
jul    19
ago    25
sep    34
oct    22
nov    21
dic    14
dtype: int64

In [50]:
almacen = pd.DataFrame({"entradas": entrada, "salidas": salida})
almacen

entradas  salidas
ene        11        9
feb        18       26
mar        12       18
abr        16       15
may         9        6
jun        16       22
jul        22       19
ago        28       25
sep        31       34
oct        29       22
nov        30       21
dic        12       14

In [53]:
almacen["neto"] = almacen.entradas - almacen.salidas
almacen

entradas  salidas  neto
ene        11        9     2
feb        18       26    -8
mar        12       18    -6
abr        16       15     1
may         9        6     3
jun        16       22    -6
jul        22       19     3
ago        28       25     3
sep        31       34    -3
oct        29       22     7
nov        30       21     9
dic        12       14    -2

In [54]:
almacen.describe()

entradas    salidas       neto
count  12.00000  12.000000  12.000000
mean   19.50000  19.250000   0.250000
std     8.16311   7.641097   5.310795
min     9.00000   6.000000  -8.000000
25%    12.00000  14.750000  -3.750000
50%    17.00000  20.000000   1.500000
75%    28.25000  22.750000   3.000000
max    31.00000  34.000000   9.000000

In [55]:
almacen.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, ene to dic
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   entradas  12 non-null     int64
 1   salidas   12 non-null     int64
 2   neto      12 non-null     int64
dtypes: int64(3)
memory usage: 684.0+ bytes


In [57]:
serie = pd.Series([3,1,2,1,1,4,1,2, np.nan])
serie

0    3.0
1    1.0
2    2.0
3    1.0
4    1.0
5    4.0
6    1.0
7    2.0
8    NaN
dtype: float64

In [59]:
serie.value_counts(dropna = False)

1.0    4
2.0    2
3.0    1
4.0    1
NaN    1
dtype: int64

In [62]:
serie.value_counts(bins=5)

(0.996, 1.6]    4
(1.6, 2.2]      2
(2.8, 3.4]      1
(3.4, 4.0]      1
(2.2, 2.8]      0
dtype: int64